language: node_js
node_js:
  - "6.11.5"

install:
  - npm i -g yarn && yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master