language: node_js
node_js:
  - "6.11.5"
before_script:
  - npm install
script:
  - npm run build
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  verbose: true
  local_dir: dist
  on:
    branch: master